name: 每日打卡

on:
  workflow_dispatch:
  schedule:
    - cron: '59 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 更新为中国时间
        run: |
          sudo rm -rf /etc/localtime 
          sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: 安装requests
        run: |
          python -m pip install requests
      - name: 运行自动打卡脚本
        run: |
          python3 ./main/index.py
      - name: 推送文件
        run: |
          git config --global user.email tzc_david@163.com
          git config --global user.name DavidTZC
          git add .
          git commit -m "Github Actions" -a || echo "day update"
      - name: 推送day.txt
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
